### ISSUE TITLE
Google Id token

### ISSUE THREAD

**Issue by lacosto** [StansAssets/Development#35]
I really liked this plugin (BUT i need google idToken)

I read a post from 2014 and you didn't provide the google idToken, only the access token. 
Here is the link to the post: https://forum.unity3d.com/threads/released-android-native-plugin.201468/page-31#post-2658579

Is there a way to retrieve the google idToken?

**Comment by AlexYaremenko** [comment]
Как и предполагалось, это функционал уже есть
`GooglePlayManager.Instance.LoadToken ("account_name", "scopes");`

**Comment by AlexYaremenko** [comment]
Чувак вообще не то имел в виду, что было в описании таска.
Будьте, пожалуйста, внимательны при создании таска.
Спасибо

Hello,

No problem, but what i need is a call to [this](https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInAccount#getIdToken()) Android API method. Because i need the Google idToken to authenticate with my backend server =D.

Thanks in advanced and if i didn't get myself clear just ask me any question.
